title: Abtion guidelines
email: meh@abtion.com
baseurl: '/guidelines'
url: '' # the base hostname & protocol for your site, e.g. http://example.com
github_username: abtion
remote_theme: abtion/github-pages-theme
